import type { GlossaryTerm } from "./types";

const t = (
  id: string,
  arabicTerm: string,
  transliteration: string,
  definition: string,
  category: string
): GlossaryTerm => ({ id, arabicTerm, transliteration, definition, category });

/** 110+ essential terms, alphabetized by transliteration. */
export const glossaryTerms: GlossaryTerm[] = [
  t("g-adhan", "أَذَان", "Adhan", "The call to prayer announced before each of the five daily prayers.", "Fiqh"),
  t("g-ahad", "آحَاد", "Ahad", "A hadith narrated through a limited number of chains, below the level of mutawatir.", "Hadith"),
  t("g-ahlus-sunnah", "أَهْلُ السُّنَّةِ وَالْجَمَاعَة", "Ahlus Sunnah wal-Jama'ah", "The people who hold to the Sunnah of the Prophet ﷺ and the way of his Companions, avoiding innovation and division.", "Aqeedah"),
  t("g-alhamdulillah", "الْحَمْدُ لِلَّه", "Alhamdulillah", "\"All praise is due to Allah\" — the expression of gratitude and praise to Allah.", "General"),
  t("g-amanah", "أَمَانَة", "Amanah", "A trust or responsibility that must be discharged faithfully.", "General"),
  t("g-aqeedah", "عَقِيدَة", "Aqeedah", "Creed; the matters of belief a Muslim ties his heart to — concerning Allah, His angels, books, messengers, the Last Day and the decree.", "Aqeedah"),
  t("g-arkan", "أَرْكَان", "Arkan", "Pillars; the essential components of an act of worship without which it is invalid.", "Fiqh"),
  t("g-asma-sifat", "الأَسْمَاءُ وَالصِّفَات", "Asma wa's-Sifat", "Allah's names and attributes, affirmed as revealed — without distortion, denial, asking how, or likening to creation.", "Aqeedah"),
  t("g-athar", "أَثَر", "Athar", "A report transmitted from a Companion or one of the Salaf, as distinct from a hadith of the Prophet ﷺ.", "Hadith"),
  t("g-ayah", "آيَة", "Ayah", "A verse of the Quran; literally a \"sign\" pointing to Allah.", "Quran"),
  t("g-barakah", "بَرَكَة", "Barakah", "Blessing; divinely placed increase and goodness in something.", "General"),
  t("g-basmalah", "بَسْمَلَة", "Basmalah", "The phrase \"Bismillah ir-Rahman ir-Raheem\" — in the name of Allah, the Most Merciful, the Bestower of mercy.", "Quran"),
  t("g-bidah", "بِدْعَة", "Bid'ah", "Innovation in religion: a newly invented act of worship with no basis in the Quran or Sunnah. Every bid'ah in worship is misguidance.", "Aqeedah"),
  t("g-daeef", "ضَعِيف", "Da'eef", "A weak hadith: one failing the conditions of authenticity in its chain or text.", "Hadith"),
  t("g-dawah", "دَعْوَة", "Da'wah", "Inviting people to Allah — to tawheed and obedience — with knowledge, wisdom and good admonition.", "Dawah"),
  t("g-deen", "دِين", "Deen", "Religion; the complete way of life Allah legislated — belief, worship, dealings and character.", "General"),
  t("g-dhikr", "ذِكْر", "Dhikr", "Remembrance of Allah with the tongue and heart, using legislated words of praise and glorification.", "General"),
  t("g-dua", "دُعَاء", "Du'a", "Supplication; asking Allah directly. The Prophet ﷺ said du'a is worship — so it may be directed to none but Allah.", "Aqeedah"),
  t("g-fajr", "فَجْر", "Fajr", "The dawn; the first obligatory prayer of the day, prayed before sunrise.", "Fiqh"),
  t("g-fatwa", "فَتْوَى", "Fatwa", "A religious verdict issued by a qualified scholar in answer to a question.", "Fiqh"),
  t("g-fiqh", "فِقْه", "Fiqh", "Understanding of the practical rulings of the Shariah — worship, transactions, family law — derived from the evidences.", "Fiqh"),
  t("g-fitnah", "فِتْنَة", "Fitnah", "Trial, tribulation or temptation that tests faith; also used for discord among people.", "General"),
  t("g-fitrah", "فِطْرَة", "Fitrah", "The innate natural disposition upon which Allah created mankind — inclining to tawheed before external influences corrupt it.", "Aqeedah"),
  t("g-ghayb", "غَيْب", "Ghayb", "The unseen: everything beyond human perception that is known only through revelation — the angels, the grave, the Last Day.", "Aqeedah"),
  t("g-ghusl", "غُسْل", "Ghusl", "The full ritual bath required to remove major impurity.", "Fiqh"),
  t("g-hadith", "حَدِيث", "Hadith", "A transmitted report of the Prophet's ﷺ statements, actions, approvals or descriptions.", "Hadith"),
  t("g-hafiz", "حَافِظ", "Hafiz", "One who has memorized the entire Quran; in hadith science, a master memorizer of narrations.", "Quran"),
  t("g-hajj", "حَجّ", "Hajj", "The pilgrimage to the Sacred House in Makkah — the fifth pillar of Islam, obligatory once upon the able.", "Fiqh"),
  t("g-halal", "حَلَال", "Halal", "That which Allah has made lawful.", "Fiqh"),
  t("g-hanif", "حَنِيف", "Hanif", "One who inclines away from shirk to pure tawheed — the description of Ibrahim عليه السلام.", "Aqeedah"),
  t("g-haram", "حَرَام", "Haram", "That which Allah has forbidden; committing it is sin and leaving it is worship.", "Fiqh"),
  t("g-hasan", "حَسَن", "Hasan", "A \"good\" hadith: authentic and acceptable as proof, though below sahih in precision of narrators.", "Hadith"),
  t("g-hijrah", "هِجْرَة", "Hijrah", "Migration for the sake of Allah — historically, the Prophet's ﷺ move from Makkah to Madinah.", "General"),
  t("g-hukm", "حُكْم", "Hukm", "A ruling of the Shariah concerning an action: obligatory, recommended, permissible, disliked, or forbidden.", "Fiqh"),
  t("g-ibadah", "عِبَادَة", "Ibadah", "Worship: a comprehensive term for everything Allah loves and is pleased with, of statements and actions, inward and outward.", "Aqeedah"),
  t("g-ihsan", "إِحْسَان", "Ihsan", "The highest level of the religion: to worship Allah as though you see Him — and though you do not see Him, He sees you.", "Aqeedah"),
  t("g-ijma", "إِجْمَاع", "Ijma'", "The consensus of the qualified scholars of the ummah on a ruling — a binding proof in Islam.", "Fiqh"),
  t("g-ikhlas", "إِخْلَاص", "Ikhlas", "Sincerity: purifying one's worship so that it is done for Allah alone, seeking neither praise nor position.", "Aqeedah"),
  t("g-ilm", "عِلْم", "Ilm", "Knowledge — in the Shariah's usage: knowledge of Allah, His religion and His Messenger ﷺ, built on evidence.", "General"),
  t("g-imam", "إِمَام", "Imam", "A leader — of the prayer, or a scholar of great standing followed in knowledge.", "General"),
  t("g-iman", "إِيمَان", "Iman", "Faith: statement of the tongue, belief of the heart and action of the limbs; it increases with obedience and decreases with sin.", "Aqeedah"),
  t("g-iqamah", "إِقَامَة", "Iqamah", "The second call announcing that the congregational prayer is beginning.", "Fiqh"),
  t("g-isnad", "إِسْنَاد", "Isnad", "The chain of narrators through which a hadith is transmitted — the science that preserved the Sunnah.", "Hadith"),
  t("g-istighfar", "اِسْتِغْفَار", "Istighfar", "Seeking Allah's forgiveness, especially with the words \"astaghfirullah\".", "General"),
  t("g-istiwa", "اِسْتِوَاء", "Istiwa", "Allah's rising over the Throne, affirmed as He revealed it: the rising is known, the how is unknown, and asking about the how is an innovation.", "Aqeedah"),
  t("g-itikaf", "اِعْتِكَاف", "I'tikaf", "Devotional seclusion in the mosque, especially in the last ten nights of Ramadan.", "Fiqh"),
  t("g-jahiliyyah", "جَاهِلِيَّة", "Jahiliyyah", "The pre-Islamic age of ignorance; also any practice that belongs to it.", "General"),
  t("g-jibreel", "جِبْرِيل", "Jibreel", "The angel entrusted with bringing revelation to the prophets — the greatest of the angels.", "Aqeedah"),
  t("g-jinn", "جِنّ", "Jinn", "A created world of beings made from smokeless fire, unseen by us, accountable like mankind for worshipping Allah.", "Aqeedah"),
  t("g-jumuah", "جُمُعَة", "Jumu'ah", "Friday; the weekly congregational prayer and sermon that replaces Dhuhr for men.", "Fiqh"),
  t("g-kabah", "كَعْبَة", "Ka'bah", "The Sacred House in Makkah built by Ibrahim and Isma'il, the direction of prayer for all Muslims.", "General"),
  t("g-kufr", "كُفْر", "Kufr", "Disbelief: rejection of Allah or of what His Messenger ﷺ came with, whether by denial, arrogance or aversion.", "Aqeedah"),
  t("g-la-ilaha", "لَا إِلَٰهَ إِلَّا اللَّه", "La ilaha illa Allah", "The word of tawheed: none has the right to be worshipped except Allah — negating worship of all else, affirming it for Him alone.", "Aqeedah"),
  t("g-madhhab", "مَذْهَب", "Madhhab", "A school of jurisprudence — Hanafi, Maliki, Shafi'i or Hanbali — each a scholarly methodology for deriving rulings.", "Fiqh"),
  t("g-makruh", "مَكْرُوه", "Makruh", "Disliked: an act better left; leaving it is rewarded and doing it is not sinful.", "Fiqh"),
  t("g-manhaj", "مَنْهَج", "Manhaj", "Methodology: the path one takes in creed, learning, practice and da'wah — soundest when it follows the Salaf.", "Aqeedah"),
  t("g-masjid", "مَسْجِد", "Masjid", "A mosque; literally, a place of prostration.", "General"),
  t("g-matn", "مَتْن", "Matn", "The text of a hadith (as opposed to its chain); also a concise classical text composed for study, like Thalathat al-Usul.", "Hadith"),
  t("g-mubah", "مُبَاح", "Mubah", "Permissible: an act carrying neither reward nor sin in itself.", "Fiqh"),
  t("g-mufti", "مُفْتِي", "Mufti", "A scholar qualified to issue fatawa.", "Fiqh"),
  t("g-muhaddith", "مُحَدِّث", "Muhaddith", "A scholar of hadith — its chains, narrators, texts and grading.", "Hadith"),
  t("g-mushrik", "مُشْرِك", "Mushrik", "One who commits shirk, directing worship to others besides Allah.", "Aqeedah"),
  t("g-mustahabb", "مُسْتَحَبّ", "Mustahabb", "Recommended: rewarded if done, not sinful if left.", "Fiqh"),
  t("g-mutawatir", "مُتَوَاتِر", "Mutawatir", "A hadith transmitted by so many narrators at every level that fabrication is impossible.", "Hadith"),
  t("g-nabi", "نَبِيّ", "Nabi", "A prophet: a man given revelation from Allah. Every messenger is a prophet, but not every prophet a messenger.", "Aqeedah"),
  t("g-nahw", "نَحْو", "Nahw", "Arabic grammar — the science of sentence structure and case endings, classically begun with al-Ajurrumiyyah.", "Arabic"),
  t("g-nifaq", "نِفَاق", "Nifaq", "Hypocrisy: displaying Islam while concealing disbelief (major), or having traits like lying and betraying trusts (minor).", "Aqeedah"),
  t("g-niyyah", "نِيَّة", "Niyyah", "Intention: the heart's resolve that distinguishes worship from habit — \"actions are only by intentions\".", "Fiqh"),
  t("g-nisab", "نِصَاب", "Nisab", "The minimum threshold of wealth upon which zakah becomes due.", "Fiqh"),
  t("g-qadar", "قَدَر", "Qadar", "The divine decree: Allah's knowledge, writing, will and creation of all things — the sixth pillar of iman.", "Aqeedah"),
  t("g-qiblah", "قِبْلَة", "Qiblah", "The direction of prayer, toward the Ka'bah in Makkah.", "Fiqh"),
  t("g-qiyam", "قِيَامُ اللَّيْل", "Qiyam al-Layl", "Voluntary prayer in the night, the most virtuous prayer after the obligatory ones.", "Fiqh"),
  t("g-quran", "قُرْآن", "Quran", "The speech of Allah revealed to Muhammad ﷺ — recited in worship, preserved unaltered, the final revelation.", "Quran"),
  t("g-rakah", "رَكْعَة", "Rak'ah", "One complete unit of prayer: standing, bowing, and two prostrations.", "Fiqh"),
  t("g-ramadan", "رَمَضَان", "Ramadan", "The ninth month of the Islamic calendar, in which fasting is obligatory and the Quran was sent down.", "Fiqh"),
  t("g-rasul", "رَسُول", "Rasul", "A messenger: a prophet sent with a message to convey to a people.", "Aqeedah"),
  t("g-riba", "رِبَا", "Riba", "Usury/interest — increase stipulated in loans or unequal exchange of like currencies; among the gravest of sins.", "Fiqh"),
  t("g-riya", "رِيَاء", "Riya", "Performing worship to be seen and praised by people — the \"hidden shirk\" the Prophet ﷺ feared for his ummah.", "Aqeedah"),
  t("g-rububiyyah", "رُبُوبِيَّة", "Rububiyyah", "Allah's Lordship: His oneness in creating, owning, providing and governing all things.", "Aqeedah"),
  t("g-ruqyah", "رُقْيَة", "Ruqyah", "Legislated healing through recitation of the Quran and authentic supplications.", "Fiqh"),
  t("g-sabr", "صَبْر", "Sabr", "Patience: restraining the soul upon obedience, away from sin, and under the decree.", "General"),
  t("g-sadaqah", "صَدَقَة", "Sadaqah", "Voluntary charity, given at any time and in any amount.", "Fiqh"),
  t("g-sahabah", "صَحَابَة", "Sahabah", "The Companions: those who met the Prophet ﷺ believing in him and died upon Islam — the best generation.", "General"),
  t("g-sahih", "صَحِيح", "Sahih", "Authentic: a hadith whose chain is connected through upright, precise narrators, free of defects.", "Hadith"),
  t("g-salaf", "سَلَف", "Salaf", "The righteous predecessors: the first three praised generations — the Companions, the Tabi'un, and their followers.", "Aqeedah"),
  t("g-salah", "صَلَاة", "Salah", "The prescribed prayer — the second pillar of Islam, performed five times daily.", "Fiqh"),
  t("g-sarf", "صَرْف", "Sarf", "Arabic morphology: the science of word patterns and derivation.", "Arabic"),
  t("g-sawm", "صَوْم", "Sawm", "Fasting: abstaining from food, drink and marital relations from true dawn to sunset as worship.", "Fiqh"),
  t("g-seerah", "سِيرَة", "Seerah", "The biography of the Prophet ﷺ.", "General"),
  t("g-shahadah", "شَهَادَة", "Shahadah", "The testimony of faith: none has the right to be worshipped except Allah, and Muhammad is His Messenger.", "Aqeedah"),
  t("g-shariah", "شَرِيعَة", "Shari'ah", "The revealed law of Islam in its entirety — creed, worship, dealings and ethics.", "Fiqh"),
  t("g-shaytan", "شَيْطَان", "Shaytan", "Satan — Iblis and his followers among jinn and men who call away from Allah.", "Aqeedah"),
  t("g-shirk", "شِرْك", "Shirk", "Associating partners with Allah in His lordship, worship, or names and attributes — the one sin not forgiven if died upon unrepentant.", "Aqeedah"),
  t("g-shubhah", "شُبْهَة", "Shubhah", "A doubt or specious argument that beautifies falsehood; treated by returning to clear texts and firm scholars.", "Aqeedah"),
  t("g-sunnah", "سُنَّة", "Sunnah", "The Prophet's ﷺ way: his statements, actions and approvals — the second revelation alongside the Quran.", "Hadith"),
  t("g-surah", "سُورَة", "Surah", "A chapter of the Quran; there are 114.", "Quran"),
  t("g-tabiun", "تَابِعُون", "Tabi'un", "The generation who learned from the Companions — the second of the praised generations.", "General"),
  t("g-tafsir", "تَفْسِير", "Tafsir", "Explanation of the Quran — soundest when the Quran is explained by the Quran, the Sunnah, and the understanding of the Salaf.", "Quran"),
  t("g-taghut", "طَاغُوت", "Taghut", "Everything worshipped, followed or obeyed besides Allah while it is pleased with that — disbelief in it is half of the shahadah.", "Aqeedah"),
  t("g-taharah", "طَهَارَة", "Taharah", "Purification from ritual impurity and filth — the key to the prayer.", "Fiqh"),
  t("g-tahrif", "تَحْرِيف", "Tahrif", "Distorting the wording or meaning of Allah's names and attributes — one of the four errors the Salafi creed avoids.", "Aqeedah"),
  t("g-tajweed", "تَجْوِيد", "Tajweed", "The science of reciting the Quran correctly, giving every letter its right.", "Quran"),
  t("g-takbir", "تَكْبِير", "Takbir", "Saying \"Allahu Akbar\" — Allah is greater than everything.", "Fiqh"),
  t("g-takyif", "تَكْيِيف", "Takyif", "Asking or asserting *how* Allah's attributes are — negated, since the how is known only to Him.", "Aqeedah"),
  t("g-talbiyah", "تَلْبِيَة", "Talbiyah", "The pilgrim's proclamation: \"Labbayk Allahumma labbayk...\" — Here I am, O Allah, here I am; You have no partner.", "Fiqh"),
  t("g-tamthil", "تَمْثِيل", "Tamthil", "Likening Allah's attributes to those of creation — negated by \"there is nothing like Him\" (42:11).", "Aqeedah"),
  t("g-taqwa", "تَقْوَى", "Taqwa", "Mindful fear of Allah: placing a shield between yourself and His anger by doing what He commands and leaving what He forbids.", "General"),
  t("g-tashahhud", "تَشَهُّد", "Tashahhud", "The sitting testimony recited in prayer, containing the greeting and the shahadatayn.", "Fiqh"),
  t("g-tatil", "تَعْطِيل", "Ta'til", "Denying or stripping away Allah's names and attributes — the error of the extreme negators.", "Aqeedah"),
  t("g-tawaf", "طَوَاف", "Tawaf", "Circumambulating the Ka'bah seven times in worship.", "Fiqh"),
  t("g-tawakkul", "تَوَكُّل", "Tawakkul", "Reliance upon Allah: entrusting outcomes to Him while taking the means He legislated.", "Aqeedah"),
  t("g-tawbah", "تَوْبَة", "Tawbah", "Repentance: leaving the sin, regretting it, resolving not to return — and restoring rights if others were wronged.", "General"),
  t("g-tawheed", "تَوْحِيد", "Tawheed", "Singling out Allah alone — in His lordship, His worship, and His names and attributes. The core of Islam and the message of every prophet.", "Aqeedah"),
  t("g-tayammum", "تَيَمُّم", "Tayammum", "Dry purification with clean earth when water is unavailable or harmful.", "Fiqh"),
  t("g-ulama", "عُلَمَاء", "Ulama", "The scholars — the inheritors of the prophets, who carry knowledge with evidence.", "General"),
  t("g-uluhiyyah", "أُلُوهِيَّة", "Uluhiyyah", "Allah's sole right to worship: the tawheed contained in \"la ilaha illa Allah\" and the point over which the messengers were sent.", "Aqeedah"),
  t("g-ummah", "أُمَّة", "Ummah", "The global community of Muslims; also, a nation to whom a messenger was sent.", "General"),
  t("g-umrah", "عُمْرَة", "Umrah", "The lesser pilgrimage: ihram, tawaf and sa'i, performable at any time of year.", "Fiqh"),
  t("g-usul", "أُصُول", "Usul", "Foundations or principles — as in usul al-din (foundations of the religion) and usul al-fiqh (principles of jurisprudence).", "General"),
  t("g-wahy", "وَحْي", "Wahy", "Revelation: Allah's communication to His prophets, whether Quran or Sunnah.", "Quran"),
  t("g-wajib", "وَاجِب", "Wajib", "Obligatory: rewarded if done, sinful if abandoned.", "Fiqh"),
  t("g-wudu", "وُضُوء", "Wudu", "Ablution: the washing legislated before prayer — a condition for its validity.", "Fiqh"),
  t("g-zakah", "زَكَاة", "Zakah", "The obligatory annual due on qualifying wealth — the third pillar of Islam, purifying giver and property.", "Fiqh"),
];
