/**
 * Generates supabase/seed.sql from the canonical TypeScript content in
 * lib/content. Run with: npm run seed:generate
 *
 * The TS content is the single source of truth: the app serves it directly
 * in demo mode, and this script materializes the identical data for Postgres.
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  departments,
  modules,
  allLessons,
  allQuizzes,
  glossaryTerms,
  resources,
  fatawa,
} from "../lib/content/index";

const q = (v: string | null | undefined): string =>
  v === null || v === undefined ? "NULL" : `'${v.replace(/'/g, "''")}'`;

const qj = (v: unknown): string => `${q(JSON.stringify(v))}::jsonb`;

const n = (v: number | null | undefined): string =>
  v === null || v === undefined ? "NULL" : String(v);

const b = (v: boolean): string => (v ? "true" : "false");

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts — do not edit by hand.",
  "-- Idempotent: clears content tables first (user tables are untouched).",
  "begin;",
  "delete from public.fatawa;",
  "delete from public.resources;",
  "delete from public.glossary_terms;",
  "delete from public.quiz_questions;",
  "delete from public.quizzes;",
  "delete from public.videos;",
  "delete from public.proofs;",
  "delete from public.lessons;",
  "delete from public.modules;",
  "delete from public.departments;",
  "",
];

for (const d of departments) {
  lines.push(
    `insert into public.departments (id, slug, name, arabic_name, description, icon, display_order, is_active, prerequisite_module_id, prerequisite_note) values (${q(d.id)}, ${q(d.slug)}, ${q(d.name)}, ${q(d.arabicName)}, ${q(d.description)}, ${q(d.icon)}, ${n(d.displayOrder)}, ${b(d.isActive)}, ${q(d.prerequisiteModuleId)}, ${q(d.prerequisiteNote)});`
  );
}
lines.push("");

for (const m of modules) {
  lines.push(
    `insert into public.modules (id, department_id, slug, name, description, display_order, prerequisite_module_id, estimated_minutes) values (${q(m.id)}, ${q(m.departmentId)}, ${q(m.slug)}, ${q(m.name)}, ${q(m.description)}, ${n(m.displayOrder)}, ${q(m.prerequisiteModuleId)}, ${n(m.estimatedMinutes)});`
  );
}
lines.push("");

for (const l of allLessons) {
  lines.push(
    `insert into public.lessons (id, module_id, slug, title, content_html, display_order, video_youtube_url, video_scholar, video_title, book_recommendations, based_on) values (${q(l.id)}, ${q(l.moduleId)}, ${q(l.slug)}, ${q(l.title)}, ${q(l.content)}, ${n(l.displayOrder)}, ${q(l.videoYoutubeUrl)}, ${q(l.videoScholar)}, ${q(l.videoTitle)}, ${qj(l.bookRecommendations)}, ${q(l.basedOn)});`
  );
  for (const p of l.proofs) {
    lines.push(
      `insert into public.proofs (id, lesson_id, type, arabic_text, english_translation, reference, display_order) values (${q(p.id)}, ${q(p.lessonId)}, ${q(p.type)}, ${q(p.arabicText)}, ${q(p.englishTranslation)}, ${q(p.reference)}, ${n(p.displayOrder)});`
    );
  }
  // Video metadata row (swappable without redeploy) — created even when the
  // URL is pending so editors can fill it in from the dashboard.
  lines.push(
    `insert into public.videos (id, lesson_id, youtube_url, title, scholar, topic) values (${q(`video-${l.id}`)}, ${q(l.id)}, ${q(l.videoYoutubeUrl)}, ${q(l.videoTitle)}, ${q(l.videoScholar)}, ${q(l.title)});`
  );
}
lines.push("");

for (const quiz of allQuizzes) {
  lines.push(
    `insert into public.quizzes (id, module_id) values (${q(quiz.id)}, ${q(quiz.moduleId)});`
  );
  for (const question of quiz.questions) {
    lines.push(
      `insert into public.quiz_questions (id, quiz_id, question_text, options, correct_answer_index, explanation, topic_tag, difficulty) values (${q(question.id)}, ${q(question.quizId)}, ${q(question.questionText)}, ${qj(question.options)}, ${n(question.correctAnswerIndex)}, ${q(question.explanation)}, ${q(question.topicTag)}, ${q(question.difficulty)});`
    );
  }
}
lines.push("");

for (const t of glossaryTerms) {
  lines.push(
    `insert into public.glossary_terms (id, arabic_term, transliteration, definition, category) values (${q(t.id)}, ${q(t.arabicTerm)}, ${q(t.transliteration)}, ${q(t.definition)}, ${q(t.category)});`
  );
}
lines.push("");

for (const r of resources) {
  lines.push(
    `insert into public.resources (id, department_id, title, author, type, url, description, pdf_url, cover_url) values (${q(r.id)}, ${q(r.departmentId)}, ${q(r.title)}, ${q(r.author)}, ${q(r.type)}, ${q(r.url)}, ${q(r.description)}, ${q(r.pdfUrl ?? null)}, ${q(r.coverUrl ?? null)});`
  );
}
lines.push("");

for (const f of fatawa) {
  lines.push(
    `insert into public.fatawa (id, topic, question, answer_text, scholar, source_reference, source_url, translation_credit, translation_url, category) values (${q(f.id)}, ${q(f.topic)}, ${q(f.question)}, ${q(f.answerText)}, ${q(f.scholar)}, ${q(f.sourceReference)}, ${q(f.sourceUrl ?? null)}, ${q(f.translationCredit ?? null)}, ${q(f.translationUrl ?? null)}, ${q(f.category)});`
  );
}

lines.push("commit;", "");

const outPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "supabase",
  "seed.sql"
);
writeFileSync(outPath, lines.join("\n"), "utf8");

console.log(
  `seed.sql written: ${departments.length} departments, ${modules.length} modules, ${allLessons.length} lessons, ${allLessons.reduce((s, l) => s + l.proofs.length, 0)} proofs, ${allQuizzes.reduce((s, z) => s + z.questions.length, 0)} quiz questions, ${glossaryTerms.length} glossary terms, ${resources.length} resources, ${fatawa.length} fatawa.`
);
